from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
OUTPUT = DOCS / "project_structure.md"

ENTRYPOINTS = [
    "app.py",
    "ops_copilot.py",
    "ops_copilot_gui.py",
    "cp_copilot_gui.py",
    "solve_contest.py",
    "solve_hard_problem.py",
    "solve_olympiad.py",
    "vlso_demo.py",
]

TOOL_GROUPS = {
    "tools/corpus": "corpus ingest, manifests, memory refresh, and hierarchy rebuild",
    "tools/cp": "competitive-programming corpus, episode ingest, and parser training",
    "tools/eval": "evaluation and benchmark CLIs",
    "tools/ops": "operations-copilot labeling and feedback utilities",
    "tools/vlso": "vision-language semantic operator memory utilities",
    "tools/maintenance": "maintenance and model-cache helpers",
}

SRC_GROUPS = {
    "src/semop/vlso": "shared visual-language operator space, geometry/topology, and visual memory",
    "src/semop": "reasoning core, CP engine, ops copilot, symbolic solvers, and corpus learning",
}

EXCLUDES = {".git", ".venv312", "__pycache__", ".tmp", "models", "data"}


def list_files(relative_dir: str) -> list[str]:
    directory = ROOT / relative_dir
    if not directory.exists():
        return []
    return sorted(path.name for path in directory.iterdir() if path.is_file())


def list_subdirs(relative_dir: str) -> list[str]:
    directory = ROOT / relative_dir
    if not directory.exists():
        return []
    return sorted(path.name for path in directory.iterdir() if path.is_dir() and path.name not in EXCLUDES)


def generate() -> str:
    lines: list[str] = []
    lines.append("# Project Structure")
    lines.append("")
    lines.append("This file is generated by `tools/maintenance/update_code_structure_docs.py`.")
    lines.append("Run that script after moving files or adding new modules.")
    lines.append("")
    lines.append("## Root Entry Points")
    lines.append("")
    for name in ENTRYPOINTS:
        lines.append(f"- `{name}`")
    lines.append("")
    lines.append("## Tooling Directories")
    lines.append("")
    for directory, description in TOOL_GROUPS.items():
        lines.append(f"### `{directory}`")
        lines.append("")
        lines.append(description + ".")
        lines.append("")
        for name in list_files(directory):
            lines.append(f"- `{directory}/{name}`")
        lines.append("")
    lines.append("## Source Directories")
    lines.append("")
    for directory, description in SRC_GROUPS.items():
        lines.append(f"### `{directory}`")
        lines.append("")
        lines.append(description + ".")
        lines.append("")
        for name in list_files(directory):
            lines.append(f"- `{directory}/{name}`")
        lines.append("")
    lines.append("## Top-Level Directories")
    lines.append("")
    for name in list_subdirs("."):
        lines.append(f"- `{name}/`")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUTPUT.write_text(generate(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
